from typing import Protocol

from hornet.entities import Rental

class RentalRepository(Protocol):
    def add(self, rental: Rental) -> Rental: ...
    def get(self, rental_id: int) -> Rental | None: ...
    def get_open_for_car(self, car_id: int) -> Rental | None: ...
    def find_all(self, limit: int | None = None, offset: int = 0) -> list[Rental]: ...
    def find_open(self, limit: int | None = None, offset: int = 0) -> list[Rental]: ...
    def end(self, rental: Rental) -> Rental: ...
    def count_open(self) -> int: ...
    def has_any_for_car(self, car_id: int) -> bool: ...
