from typing import Protocol

from hornet.commands import AddCar, UpdateCar
from hornet.entities import Car, CarStatus

class CarService(Protocol):
    def add_car(self, command: AddCar) -> Car: ...
    def update_car(self, command: UpdateCar) -> Car: ...
    def delete_car(self, car_id: int) -> None: ...
    def list_cars(self, status: CarStatus | None, limit: int | None, offset: int) -> list[Car]: ...
