from typing import Protocol

from hornet.entities import Car, CarStatus

class CarRepository(Protocol):
    def add(self, car: Car) -> Car: ...
    def get(self, car_id: int) -> Car | None: ...
    def update(self, car: Car) -> Car: ...
    def delete(self, car_id: int) -> None: ...
    def find_all(self, status: CarStatus | None = None, limit: int | None = None, offset: int = 0) -> list[Car]: ...
    def count_by_status(self, status: CarStatus) -> int: ...
